name: Build Check on PRs

on:
  pull_request:
    branches:
      - '**'

jobs:
  lint-and-format:
    name: Lint/Format/Build Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build (includes formatting, linting, and type checking)
        run: npm run build
